trigger:
- main

pr:
- main

jobs:
  - job: DockerPipeline
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      displayName: Check, build and release images
      inputs:
        filePath: development/build.sh
      env:
        DOCKERHUB_AUTH: $(DOCKERHUB_AUTH)
        GITHUB_TOKEN: $(GITHUB_TOKEN)
