trigger:
- main

pr:
- main

jobs:  
  - job: DockerPipeline 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      displayName: Build all rserver images
      inputs:
        filePath: .azure/build_docker.bash
